name: nop_db_sqlite
description: nop_db sqlite implemention
version: 0.0.2
homepage:
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  nop_db:
    path: ../nop_db
  sqlite3_windows_dll:
    path: ../sqlite3_windows_dll
  sqlite3: ^1.1.2
  sqlite3_flutter_libs: ^0.5.0
  drift: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
