name: nop_db_sqlite
description: nop_db sqlite implemention
version: 0.0.3
homepage:
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  nop:
    git:
      url: https://github.com/sersr/nop.git
  nop_db:
    git:
      url: https://github.com/sersr/nop_db.git
  sqlite3_windows_dll:
    git:
      url: https://github.com/sersr/sqlite3_windows_dll.git
  sqlite3: ^1.1.2
  sqlite3_flutter_libs: ^0.5.0
  drift: ^1.1.0
dependency_overrides:
  nop:
    path: ../nop
  nop_db:
    path: ../nop_db

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
