name: nop_db_sqlite
description: nop_db sqlite implemention
version: 0.0.4
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  nop: any
  nop_db:
    git:
      url: https://github.com/sersr/nop_db.git
  sqlite3_windows_dll:
    git:
      url: https://github.com/sersr/sqlite3_windows_dll.git
  # sqlite3: ">=1.1.2 <3.0.0"
  sqlite3: any
  sqlite3_flutter_libs: ">=0.5.0 <1.0.0"
  drift: ">=1.1.0 <2.0.0"
dependency_overrides:
  nop:
    path: ../nop
  nop_db:
    path: ../nop_db

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
